### ISSUE TITLE
I run your model, but it raises an error

### ISSUE THREAD

**Issue by aban77** [shiyujiao/cross_view_localization_SAFA#1]
Traceback (most recent call last):
File "train_cvusa.py", line 219, in
train(start_epoch)
File "train_cvusa.py", line 115, in train
sat_global, grd_global = SAFA(sat_x, grd_x, keep_prob, dimension, is_training)
File "/mnt/mnt1/fq/SAFA/cross_view_localization_SAFA-master/script/spatial_net.py", line 41, in SAFA
grd_w = spatial_aware(grd_local, dimension, trainable, name='spatial_grd')
File "/mnt/mnt1/fq/SAFA/cross_view_localization_SAFA-master/script/spatial_net.py", line 19, in spatial_aware
vec2 = tf.einsum('bi, ijd -> bjd', vec1, weight1) + bias1
File "/home/anaconda3/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/ops/special_math_ops.py", line 210, in einsum
axes_to_sum)
File "/home/anaconda3/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/ops/special_math_ops.py", line 256, in _einsum_reduction
raise ValueError()

**Comment by aban77** [comment]
I solved this problem by upgrading the version of tensorflow form 1.4.0 to 1.14.0
