### ISSUE TITLE
Error while testing your model on cvact, can you tell us system requirements os,python version,tensorflow version,cuda version ? 

### ISSUE THREAD

**Issue by Rodrigues-Royston** [shiyujiao/cross_view_localization_SAFA#4]
(nips_new_19) rodrigues@DL-Box:/data2/Royston/sat2ground/sota_and_existing/NIPS_19/cross_view_localization_SAFA/script$ python test_cvact.py
InputData::__init__: load ./OriNet_CVACT/CVACT_orientations/ACT_data.mat
InputData::__init__: load ./OriNet_CVACT/CVACT_orientations/ACT_data.mat  data_size = 308900
VGG16: trainable = True
VGG16: trainable = True
WARNING:tensorflow:From /data2/Royston/sat2ground/sota_and_existing/NIPS_19/cross_view_localization_SAFA/script/spatial_net.py:58: calling l2_normalize (from tensorflow.python.ops.nn_impl) with dim is deprecated and will be removed in a future version.
Instructions for updating:
dim is deprecated, use axis instead
run model...
2020-06-15 15:29:10.571581: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2020-06-15 15:29:11.032532: E tensorflow/stream_executor/cuda/cuda_driver.cc:397] failed call to cuInit: CUDA_ERROR_NO_DEVICE
2020-06-15 15:29:11.032579: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:163] retrieving CUDA diagnostic information for host: DL-Box
2020-06-15 15:29:11.032592: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:170] hostname: DL-Box
2020-06-15 15:29:11.032636: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:194] libcuda reported version is: 384.98.0
2020-06-15 15:29:11.032672: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:198] kernel reported version is: 384.98.0
2020-06-15 15:29:11.032684: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:305] kernel version seems to match DSO: 384.98.0
load model...
2020-06-15 15:29:11.240505: W tensorflow/core/framework/op_kernel.cc:1275] OP_REQUIRES failed at save_restore_v2_ops.cc:184 : Not found: Key spatial_grd/biases1 not found in checkpoint
Traceback (most recent call last):
  File "/home/rodrigues/anaconda3/envs/nips_new_19/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1278, in _do_call
    return fn(*args)
  File "/home/rodrigues/anaconda3/envs/nips_new_19/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1263, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/rodrigues/anaconda3/envs/nips_new_19/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1350, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.NotFoundError: Key spatial_grd/biases1 not found in checkpoint
	 [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rodrigues/anaconda3/envs/nips_new_19/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1725, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/home/rodrigues/anaconda3/envs/nips_new_19/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 877, in run
    run_metadata_ptr)
  File "/home/rodrigues/anaconda3/envs/nips_new_19/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1100, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/rodrigues/anaconda3/envs/nips_new_19/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1272, in _do_run
    run_metadata)
  File "/home/rodrigues/anaconda3/envs/nips_new_19/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1291, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: Key spatial_grd/biases1 not found in checkpoint
	 [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]

Caused by op 'save/RestoreV2', defined at:
  File "test_cvact.py", line 82, in <module>
    saver = tf.train.Saver(tf.global_variables(), max_to_keep=None)
  File "/home/rodrigues/anaconda3/envs/nips_new_19/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1281, in __init__
    self.build()
  File "/home/rodrigues/anaconda3/envs/nips_new_19/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1293, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/home/rodrigues/anaconda3/envs/nips_new_19/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1330, in _build
    build_save=build_save, build_restore=build_restore)
  File "/home/rodrigues/anaconda3/envs/nips_new_19/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 778, in _build_internal
    restore_sequentially, reshape)
  File "/home/rodrigues/anaconda3/envs/nips_new_19/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 397, in _AddRestoreOps
    restore_sequentially)
  File "/home/rodrigues/anaconda3/envs/nips_new_19/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 829, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "/home/rodrigues/anaconda3/envs/nips_new_19/lib/python3.5/site-packages/tensorflow/python/ops/gen_io_ops.py", line 1463, in restore_v2
    shape_and_slices=shape_and_slices, dtypes=dtypes, name=name)
  File "/home/rodrigues/anaconda3/envs/nips_new_19/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/rodrigues/anaconda3/envs/nips_new_19/lib/python3.5/site-packages/tensorflow/python/util/deprecation.py", line 454, in new_func
    return func(*args, **kwargs)
  File "/home/rodrigues/anaconda3/envs/nips_new_19/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 3155, in create_op
    op_def=op_def)
  File "/home/rodrigues/anaconda3/envs/nips_new_19/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1717, in __init__
    self._traceback = tf_stack.extract_stack()

NotFoundError (see above for traceback): Key spatial_grd/biases1 not found in checkpoint
	 [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rodrigues/anaconda3/envs/nips_new_19/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1737, in restore
    checkpointable.OBJECT_GRAPH_PROTO_KEY)
  File "/home/rodrigues/anaconda3/envs/nips_new_19/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 351, in get_tensor
    status)
  File "/home/rodrigues/anaconda3/envs/nips_new_19/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 519, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: Key _CHECKPOINTABLE_OBJECT_GRAPH not found in checkpoint

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test_cvact.py", line 95, in <module>
    saver.restore(sess, load_model_path)
  File "/home/rodrigues/anaconda3/envs/nips_new_19/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1743, in restore
    err, "a Variable name or other graph key that is missing")
tensorflow.python.framework.errors_impl.NotFoundError: Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Key spatial_grd/biases1 not found in checkpoint
	 [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]

Caused by op 'save/RestoreV2', defined at:
  File "test_cvact.py", line 82, in <module>
    saver = tf.train.Saver(tf.global_variables(), max_to_keep=None)
  File "/home/rodrigues/anaconda3/envs/nips_new_19/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1281, in __init__
    self.build()
  File "/home/rodrigues/anaconda3/envs/nips_new_19/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1293, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/home/rodrigues/anaconda3/envs/nips_new_19/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1330, in _build
    build_save=build_save, build_restore=build_restore)
  File "/home/rodrigues/anaconda3/envs/nips_new_19/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 778, in _build_internal
    restore_sequentially, reshape)
  File "/home/rodrigues/anaconda3/envs/nips_new_19/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 397, in _AddRestoreOps
    restore_sequentially)
  File "/home/rodrigues/anaconda3/envs/nips_new_19/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 829, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "/home/rodrigues/anaconda3/envs/nips_new_19/lib/python3.5/site-packages/tensorflow/python/ops/gen_io_ops.py", line 1463, in restore_v2
    shape_and_slices=shape_and_slices, dtypes=dtypes, name=name)
  File "/home/rodrigues/anaconda3/envs/nips_new_19/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/rodrigues/anaconda3/envs/nips_new_19/lib/python3.5/site-packages/tensorflow/python/util/deprecation.py", line 454, in new_func
    return func(*args, **kwargs)
  File "/home/rodrigues/anaconda3/envs/nips_new_19/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 3155, in create_op
    op_def=op_def)
  File "/home/rodrigues/anaconda3/envs/nips_new_19/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1717, in __init__
    self._traceback = tf_stack.extract_stack()

NotFoundError (see above for traceback): Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Key spatial_grd/biases1 not found in checkpoint
	 [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]

**Comment by shiyujiao** [comment]
Hi,

Thanks for reporting this issue.
The environment of my computer is:

OS: Ubuntu 16.04
Python: 3.7.4
TensorFlow: 1.13.1
Cuda: 10.0

The codes work well under the above system configuration. 

Yujiao

**Comment by shiyujiao** [comment]
> (nips_new_19) rodrigues@DL-Box:/data2/Royston/sat2ground/sota_and_existing/NIPS_19/cross_view_localization_SAFA/script$ python test_cvact.py
> InputData::**init**: load ./OriNet_CVACT/CVACT_orientations/ACT_data.mat
> InputData::**init**: load ./OriNet_CVACT/CVACT_orientations/ACT_data.mat data_size = 308900
> VGG16: trainable = True
> VGG16: trainable = True
> WARNING:tensorflow:From /data2/Royston/sat2ground/sota_and_existing/NIPS_19/cross_view_localization_SAFA/script/spatial_net.py:58: calling l2_normalize (from tensorflow.python.ops.nn_impl) with dim is deprecated and will be removed in a future version.
> Instructions for updating:
> dim is deprecated, use axis instead
> run model...
> 2020-06-15 15:29:10.571581: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
> 2020-06-15 15:29:11.032532: E tensorflow/stream_executor/cuda/cuda_driver.cc:397] failed call to cuInit: CUDA_ERROR_NO_DEVICE
> 2020-06-15 15:29:11.032579: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:163] retrieving CUDA diagnostic information for host: DL-Box
> 2020-06-15 15:29:11.032592: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:170] hostname: DL-Box
> 2020-06-15 15:29:11.032636: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:194] libcuda reported version is: 384.98.0
> 2020-06-15 15:29:11.032672: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:198] kernel reported version is: 384.98.0
> 2020-06-15 15:29:11.032684: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:305] kernel version seems to match DSO: 384.98.0
> load model...
> 2020-06-15 15:29:11.240505: W tensorflow/core/framework/op_kernel.cc:1275] OP_REQUIRES failed at save_restore_v2_ops.cc:184 : Not found: Key spatial_grd/biases1 not found in checkpoint
> Traceback (most recent call last):
> File "/home/rodrigues/anaconda3/envs/nips_new_19/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1278, in _do_call
> return fn(*args)
> File "/home/rodrigues/anaconda3/envs/nips_new_19/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1263, in _run_fn
> options, feed_dict, fetch_list, target_list, run_metadata)
> File "/home/rodrigues/anaconda3/envs/nips_new_19/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1350, in _call_tf_sessionrun
> run_metadata)
> tensorflow.python.framework.errors_impl.NotFoundError: Key spatial_grd/biases1 not found in checkpoint
> [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "/home/rodrigues/anaconda3/envs/nips_new_19/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1725, in restore
> {self.saver_def.filename_tensor_name: save_path})
> File "/home/rodrigues/anaconda3/envs/nips_new_19/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 877, in run
> run_metadata_ptr)
> File "/home/rodrigues/anaconda3/envs/nips_new_19/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1100, in _run
> feed_dict_tensor, options, run_metadata)
> File "/home/rodrigues/anaconda3/envs/nips_new_19/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1272, in _do_run
> run_metadata)
> File "/home/rodrigues/anaconda3/envs/nips_new_19/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1291, in _do_call
> raise type(e)(node_def, op, message)
> tensorflow.python.framework.errors_impl.NotFoundError: Key spatial_grd/biases1 not found in checkpoint
> [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]
> 
> Caused by op 'save/RestoreV2', defined at:
> File "test_cvact.py", line 82, in
> saver = tf.train.Saver(tf.global_variables(), max_to_keep=None)
> File "/home/rodrigues/anaconda3/envs/nips_new_19/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1281, in **init**
> self.build()
> File "/home/rodrigues/anaconda3/envs/nips_new_19/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1293, in build
> self._build(self._filename, build_save=True, build_restore=True)
> File "/home/rodrigues/anaconda3/envs/nips_new_19/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1330, in _build
> build_save=build_save, build_restore=build_restore)
> File "/home/rodrigues/anaconda3/envs/nips_new_19/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 778, in _build_internal
> restore_sequentially, reshape)
> File "/home/rodrigues/anaconda3/envs/nips_new_19/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 397, in _AddRestoreOps
> restore_sequentially)
> File "/home/rodrigues/anaconda3/envs/nips_new_19/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 829, in bulk_restore
> return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
> File "/home/rodrigues/anaconda3/envs/nips_new_19/lib/python3.5/site-packages/tensorflow/python/ops/gen_io_ops.py", line 1463, in restore_v2
> shape_and_slices=shape_and_slices, dtypes=dtypes, name=name)
> File "/home/rodrigues/anaconda3/envs/nips_new_19/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
> op_def=op_def)
> File "/home/rodrigues/anaconda3/envs/nips_new_19/lib/python3.5/site-packages/tensorflow/python/util/deprecation.py", line 454, in new_func
> return func(*args, **kwargs)
> File "/home/rodrigues/anaconda3/envs/nips_new_19/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 3155, in create_op
> op_def=op_def)
> File "/home/rodrigues/anaconda3/envs/nips_new_19/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1717, in **init**
> self._traceback = tf_stack.extract_stack()
> 
> NotFoundError (see above for traceback): Key spatial_grd/biases1 not found in checkpoint
> [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "/home/rodrigues/anaconda3/envs/nips_new_19/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1737, in restore
> checkpointable.OBJECT_GRAPH_PROTO_KEY)
> File "/home/rodrigues/anaconda3/envs/nips_new_19/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 351, in get_tensor
> status)
> File "/home/rodrigues/anaconda3/envs/nips_new_19/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 519, in **exit**
> c_api.TF_GetCode(self.status.status))
> tensorflow.python.framework.errors_impl.NotFoundError: Key _CHECKPOINTABLE_OBJECT_GRAPH not found in checkpoint
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "test_cvact.py", line 95, in
> saver.restore(sess, load_model_path)
> File "/home/rodrigues/anaconda3/envs/nips_new_19/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1743, in restore
> err, "a Variable name or other graph key that is missing")
> tensorflow.python.framework.errors_impl.NotFoundError: Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:
> 
> Key spatial_grd/biases1 not found in checkpoint
> [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]
> 
> Caused by op 'save/RestoreV2', defined at:
> File "test_cvact.py", line 82, in
> saver = tf.train.Saver(tf.global_variables(), max_to_keep=None)
> File "/home/rodrigues/anaconda3/envs/nips_new_19/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1281, in **init**
> self.build()
> File "/home/rodrigues/anaconda3/envs/nips_new_19/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1293, in build
> self._build(self._filename, build_save=True, build_restore=True)
> File "/home/rodrigues/anaconda3/envs/nips_new_19/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1330, in _build
> build_save=build_save, build_restore=build_restore)
> File "/home/rodrigues/anaconda3/envs/nips_new_19/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 778, in _build_internal
> restore_sequentially, reshape)
> File "/home/rodrigues/anaconda3/envs/nips_new_19/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 397, in _AddRestoreOps
> restore_sequentially)
> File "/home/rodrigues/anaconda3/envs/nips_new_19/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 829, in bulk_restore
> return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
> File "/home/rodrigues/anaconda3/envs/nips_new_19/lib/python3.5/site-packages/tensorflow/python/ops/gen_io_ops.py", line 1463, in restore_v2
> shape_and_slices=shape_and_slices, dtypes=dtypes, name=name)
> File "/home/rodrigues/anaconda3/envs/nips_new_19/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
> op_def=op_def)
> File "/home/rodrigues/anaconda3/envs/nips_new_19/lib/python3.5/site-packages/tensorflow/python/util/deprecation.py", line 454, in new_func
> return func(*args, **kwargs)
> File "/home/rodrigues/anaconda3/envs/nips_new_19/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 3155, in create_op
> op_def=op_def)
> File "/home/rodrigues/anaconda3/envs/nips_new_19/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1717, in **init**
> self._traceback = tf_stack.extract_stack()
> 
> NotFoundError (see above for traceback): Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:
> 
> Key spatial_grd/biases1 not found in checkpoint
> [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]

Hi,

Thanks for reporting this issue.
The environment of my computer is:

OS: Ubuntu 16.04
Python: 3.7.4
TensorFlow: 1.13.1
Cuda: 10.0

The codes work well under the above system configuration.

Yujiao
